//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFUI.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BllUser", Namespace="http://schemas.datacontract.org/2004/07/BLL.Models")]
    [System.SerializableAttribute()]
    public partial class BllUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime BirthDatek__BackingFieldField;
        
        private WCFUI.ServiceReference1.BllVisaRecord[] Cardsk__BackingFieldField;
        
        private string FirstNamek__BackingFieldField;
        
        private WCFUI.ServiceReference1.BllGender Genderk__BackingFieldField;
        
        private int Idk__BackingFieldField;
        
        private string LastNamek__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<BirthDate>k__BackingField", IsRequired=true)]
        public System.DateTime BirthDatek__BackingField {
            get {
                return this.BirthDatek__BackingFieldField;
            }
            set {
                if ((this.BirthDatek__BackingFieldField.Equals(value) != true)) {
                    this.BirthDatek__BackingFieldField = value;
                    this.RaisePropertyChanged("BirthDatek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Cards>k__BackingField", IsRequired=true)]
        public WCFUI.ServiceReference1.BllVisaRecord[] Cardsk__BackingField {
            get {
                return this.Cardsk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Cardsk__BackingFieldField, value) != true)) {
                    this.Cardsk__BackingFieldField = value;
                    this.RaisePropertyChanged("Cardsk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<FirstName>k__BackingField", IsRequired=true)]
        public string FirstNamek__BackingField {
            get {
                return this.FirstNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNamek__BackingFieldField, value) != true)) {
                    this.FirstNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("FirstNamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Gender>k__BackingField", IsRequired=true)]
        public WCFUI.ServiceReference1.BllGender Genderk__BackingField {
            get {
                return this.Genderk__BackingFieldField;
            }
            set {
                if ((this.Genderk__BackingFieldField.Equals(value) != true)) {
                    this.Genderk__BackingFieldField = value;
                    this.RaisePropertyChanged("Genderk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Id>k__BackingField", IsRequired=true)]
        public int Idk__BackingField {
            get {
                return this.Idk__BackingFieldField;
            }
            set {
                if ((this.Idk__BackingFieldField.Equals(value) != true)) {
                    this.Idk__BackingFieldField = value;
                    this.RaisePropertyChanged("Idk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<LastName>k__BackingField", IsRequired=true)]
        public string LastNamek__BackingField {
            get {
                return this.LastNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNamek__BackingFieldField, value) != true)) {
                    this.LastNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("LastNamek__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BllVisaRecord", Namespace="http://schemas.datacontract.org/2004/07/BLL.Models")]
    [System.SerializableAttribute()]
    public partial class BllVisaRecord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string Countryk__BackingFieldField;
        
        private System.DateTime ExpiryDatek__BackingFieldField;
        
        private System.DateTime StartDatek__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Country>k__BackingField", IsRequired=true)]
        public string Countryk__BackingField {
            get {
                return this.Countryk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Countryk__BackingFieldField, value) != true)) {
                    this.Countryk__BackingFieldField = value;
                    this.RaisePropertyChanged("Countryk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ExpiryDate>k__BackingField", IsRequired=true)]
        public System.DateTime ExpiryDatek__BackingField {
            get {
                return this.ExpiryDatek__BackingFieldField;
            }
            set {
                if ((this.ExpiryDatek__BackingFieldField.Equals(value) != true)) {
                    this.ExpiryDatek__BackingFieldField = value;
                    this.RaisePropertyChanged("ExpiryDatek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<StartDate>k__BackingField", IsRequired=true)]
        public System.DateTime StartDatek__BackingField {
            get {
                return this.StartDatek__BackingFieldField;
            }
            set {
                if ((this.StartDatek__BackingFieldField.Equals(value) != true)) {
                    this.StartDatek__BackingFieldField = value;
                    this.RaisePropertyChanged("StartDatek__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BllGender", Namespace="http://schemas.datacontract.org/2004/07/BLL.Models")]
    public enum BllGender : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Male = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Female = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FirstNameCriterion", Namespace="http://schemas.datacontract.org/2004/07/BLL.SearchCriteria")]
    [System.SerializableAttribute()]
    public partial class FirstNameCriterion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string firstNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LastNameCriterion", Namespace="http://schemas.datacontract.org/2004/07/BLL.SearchCriteria")]
    [System.SerializableAttribute()]
    public partial class LastNameCriterion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string lastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdCriterion", Namespace="http://schemas.datacontract.org/2004/07/BLL.SearchCriteria")]
    [System.SerializableAttribute()]
    public partial class IdCriterion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int maxIdField;
        
        private int minIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int maxId {
            get {
                return this.maxIdField;
            }
            set {
                if ((this.maxIdField.Equals(value) != true)) {
                    this.maxIdField = value;
                    this.RaisePropertyChanged("maxId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int minId {
            get {
                return this.minIdField;
            }
            set {
                if ((this.minIdField.Equals(value) != true)) {
                    this.minIdField = value;
                    this.RaisePropertyChanged("minId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IUserServiceContract")]
    public interface IUserServiceContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserServiceContract/Add", ReplyAction="http://tempuri.org/IUserServiceContract/AddResponse")]
        int Add(WCFUI.ServiceReference1.BllUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserServiceContract/Add", ReplyAction="http://tempuri.org/IUserServiceContract/AddResponse")]
        System.Threading.Tasks.Task<int> AddAsync(WCFUI.ServiceReference1.BllUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserServiceContract/Delete", ReplyAction="http://tempuri.org/IUserServiceContract/DeleteResponse")]
        void Delete(WCFUI.ServiceReference1.BllUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserServiceContract/Delete", ReplyAction="http://tempuri.org/IUserServiceContract/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(WCFUI.ServiceReference1.BllUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserServiceContract/SearchForUsers", ReplyAction="http://tempuri.org/IUserServiceContract/SearchForUsersResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFUI.ServiceReference1.BllUser))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFUI.ServiceReference1.BllVisaRecord[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFUI.ServiceReference1.BllVisaRecord))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFUI.ServiceReference1.BllGender))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFUI.ServiceReference1.FirstNameCriterion))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFUI.ServiceReference1.LastNameCriterion))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFUI.ServiceReference1.IdCriterion))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        int[] SearchForUsers(object[] criteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserServiceContract/SearchForUsers", ReplyAction="http://tempuri.org/IUserServiceContract/SearchForUsersResponse")]
        System.Threading.Tasks.Task<int[]> SearchForUsersAsync(object[] criteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserServiceContract/Save", ReplyAction="http://tempuri.org/IUserServiceContract/SaveResponse")]
        void Save();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserServiceContract/Save", ReplyAction="http://tempuri.org/IUserServiceContract/SaveResponse")]
        System.Threading.Tasks.Task SaveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserServiceContract/Load", ReplyAction="http://tempuri.org/IUserServiceContract/LoadResponse")]
        void Load();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserServiceContract/Load", ReplyAction="http://tempuri.org/IUserServiceContract/LoadResponse")]
        System.Threading.Tasks.Task LoadAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceContractChannel : WCFUI.ServiceReference1.IUserServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceContractClient : System.ServiceModel.ClientBase<WCFUI.ServiceReference1.IUserServiceContract>, WCFUI.ServiceReference1.IUserServiceContract {
        
        public UserServiceContractClient() {
        }
        
        public UserServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Add(WCFUI.ServiceReference1.BllUser user) {
            return base.Channel.Add(user);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(WCFUI.ServiceReference1.BllUser user) {
            return base.Channel.AddAsync(user);
        }
        
        public void Delete(WCFUI.ServiceReference1.BllUser user) {
            base.Channel.Delete(user);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(WCFUI.ServiceReference1.BllUser user) {
            return base.Channel.DeleteAsync(user);
        }
        
        public int[] SearchForUsers(object[] criteria) {
            return base.Channel.SearchForUsers(criteria);
        }
        
        public System.Threading.Tasks.Task<int[]> SearchForUsersAsync(object[] criteria) {
            return base.Channel.SearchForUsersAsync(criteria);
        }
        
        public void Save() {
            base.Channel.Save();
        }
        
        public System.Threading.Tasks.Task SaveAsync() {
            return base.Channel.SaveAsync();
        }
        
        public void Load() {
            base.Channel.Load();
        }
        
        public System.Threading.Tasks.Task LoadAsync() {
            return base.Channel.LoadAsync();
        }
    }
}
